import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/partials/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen w-screen bg-black text-white">
          <Nav />
          <main className="flex flex-col h-full w-full min-h-screen items-center justify-start p-4 overflow-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
